### ISSUE TITLE
Create Organizers page/area within the website

### ISSUE THREAD

**Issue by clairealyssa** [San-Francisco-Write-The-Docs/www#2]
- 1 page versus multiple pages
- Needs a layout
- How will people navigate to this page? Is it hidden or visible?

**Comment by clairealyssa** [comment]
@cwcromwell There is an existing collection (_organizers) and a blank/default page layout.

**Comment by cwcromwell** [comment]
Created content/_organizers/organizers.md.

**Comment by clairealyssa** [comment]
We'll call v1 of this done - more to come later.
