### ISSUE TITLE
Create "About Us" content

### ISSUE THREAD

**Issue by clairealyssa** [San-Francisco-Write-The-Docs/www#5]

**Comment by cwcromwell** [comment]
Saved in the `content/_about` directory.

**Comment by clairealyssa** [comment]
Commits:

- ad5a6cbe6db652d36c285c00967b5df296f1301f
- 4847b1185c29891d15bffa344edb5be6100b7f43

**Comment by clairealyssa** [comment]
@cwcromwell Check it out: https://writethedocs-sfbay.org/about/

**Comment by clairealyssa** [comment]
We'll call v1 of this done.
