### ISSUE TITLE
Write announcement about how WTD Bay Area is re-organized

### ISSUE THREAD

**Issue by cwcromwell** [San-Francisco-Write-The-Docs/www#9]
Members will need to know: 
- We'll have one meeting a month at the most
- We'll still meet in all the areas (EB, SB, SF)
- We chose to do that to make planning easier and to be consistent in presenting every month. 
- What are the benefits for members (better programming, a search for more and better venues.)

**Comment by cwcromwell** [comment]
Do we still need this announcement?

**Comment by clairealyssa** [comment]
Probably not.
